import type { Topic } from "@/lib/topics";

// P5 Mathematics draft content layer.
// Source map: content/curriculum/p5-math.json
// Rule: NCDC first, build second. This file follows the researched P5 Set One Mathematics structure.
// Status: live beta until checked against an official/trusted NCDC copy by a human reviewer.

const BETA_NOTICE = "P5 beta content: verify against official NCDC Primary Five Mathematics before market-facing release.";

export const P5_MATH_TOPICS: Topic[] = [
  {
    id: "p5-set-concepts",
    themeId: "p5-theme-sets",
    themeName: "Sets",
    title: "Set Concepts",
    estMinutes: 28,
    status: "published",
    reviewStatus: "beta",
    note: {
      intro: `${BETA_NOTICE} Set concepts help learners group objects, compare collections and use Venn diagrams in everyday situations.`,
      learningObjectives: [
        "Form and name sets from real objects or numbers.",
        "Distinguish equal, equivalent and empty sets.",
        "Find union and intersection using two-set Venn diagrams.",
      ],
      whatYouNeedToKnow: [
        "A set is a well-defined collection of objects or numbers.",
        "Equal sets contain exactly the same members; equivalent sets contain the same number of members.",
        "Union means all members in the sets, while intersection means members common to both sets.",
      ],
      worked: {
        problem: "Let A = {2, 4, 6} and B = {4, 6, 8}. Find A ∩ B and A ∪ B.",
        steps: [
          "Common members are 4 and 6, so A ∩ B = {4, 6}.",
          "All members without repetition are 2, 4, 6 and 8.",
          "Therefore A ∪ B = {2, 4, 6, 8}.",
        ],
        answer: "A ∩ B = {4, 6}; A ∪ B = {2, 4, 6, 8}.",
      },
      commonMistakes: [
        "Repeating common members when listing the union.",
        "Calling sets equal when they only have the same number of members.",
        "Forgetting that an empty set has no members.",
      ],
      recap: [
        "Equal means same members.",
        "Equivalent means same number of members.",
        "Intersection is the overlap; union is everything in the sets.",
      ],
    },
    subtopics: [
      {
        subtopicId: "p5-forming-comparing-sets",
        title: "1. Forming and comparing sets",
        modules: [
          {
            moduleId: "p5-set-meaning-types",
            title: "Sets, Equal Sets and Equivalent Sets",
            bigIdea: "A set must have a clear rule so that members can be listed correctly.",
            learnIt: [
              "Use curly brackets to list members, for example {a, e, i, o, u}.",
              "Equal sets have exactly the same members, even if the order is different.",
              "Equivalent sets have the same number of members, even when the members are different.",
            ],
            workedExample: {
              question: "Are {1, 2, 3} and {a, b, c} equal or equivalent?",
              steps: [
                "Count members in the first set: 3.",
                "Count members in the second set: 3.",
                "The members are not the same, but the number of members is the same.",
              ],
              answer: "They are equivalent sets, not equal sets.",
            },
            tryThis: {
              question: "Which pair of sets is equal?",
              choices: ["{2, 4, 6} and {6, 4, 2}", "{a, b} and {1, 2}", "{red} and {red, blue}", "{ } and {0}"],
              correct: 0,
              explanation: "Order does not matter; both sets have exactly the same members.",
            },
          },
        ],
      },
      {
        subtopicId: "p5-union-intersection-venn",
        title: "2. Union and intersection on Venn diagrams",
        modules: [
          {
            moduleId: "p5-venn-union-intersection",
            title: "Reading Two-Set Venn Diagrams",
            bigIdea: "Venn diagrams show what belongs to only one set, both sets, or neither set.",
            learnIt: [
              "The middle overlap contains members in both sets. This is the intersection.",
              "The union contains everything inside either circle, but repeated members are written once.",
              "In word problems, fill the overlap first before finding only-left and only-right parts.",
            ],
            workedExample: {
              question: "In a class, 16 learners like mangoes, 12 like oranges and 5 like both. How many like only mangoes?",
              steps: [
                "Start with the mango group: 16 learners.",
                "Remove the overlap because 5 like both.",
                "Only mangoes = 16 - 5 = 11.",
              ],
              answer: "11 learners like only mangoes.",
            },
            tryThis: {
              question: "If 20 learners like football and 6 also like netball, how many like football only?",
              choices: ["14", "20", "26", "6"],
              correct: 0,
              explanation: "Football only = 20 - 6 = 14.",
            },
          },
        ],
      },
    ],
    quiz: [
      { q: "What is a set?", choices: ["A well-defined collection", "A random noise", "A type of road", "A clock"], correct: 0, why: "A set is a clear collection of objects or numbers." },
      { q: "Which sets are equivalent?", choices: ["{a, b, c} and {1, 2, 3}", "{a} and {a, b}", "{1, 2} and {1, 2, 3}", "{ } and {0}"], correct: 0, why: "Both sets have 3 members." },
      { q: "Find {2, 4} ∪ {4, 6}.", choices: ["{2, 4, 6}", "{4}", "{2, 6}", "{2, 4, 4, 6}"], correct: 0, why: "Union lists all members without repeating 4." },
      { q: "Find {2, 4, 6} ∩ {4, 6, 8}.", choices: ["{4, 6}", "{2, 8}", "{2, 4, 6, 8}", "{ }"], correct: 0, why: "4 and 6 are common to both sets." },
      { q: "An empty set has:", choices: ["no members", "one member", "two members", "all members"], correct: 0, why: "An empty set contains no members." },
      { q: "In a Venn diagram, the overlap means:", choices: ["members in both sets", "members in no set", "only the first set", "only the second set"], correct: 0, why: "The overlap is the intersection." },
    ],
  },
  {
    id: "p5-whole-numbers",
    themeId: "p5-theme-numeracy",
    themeName: "Numeracy",
    title: "Whole Numbers",
    estMinutes: 30,
    status: "published",
    reviewStatus: "beta",
    note: {
      intro: `${BETA_NOTICE} Whole numbers build the counting, reading and place-value skills needed for all later mathematics.`,
      learningObjectives: ["Read and write whole numbers up to 999,999.", "Find place value and value of digits.", "Round whole numbers to the nearest ten thousands.", "Read and write Roman numerals up to fifty."],
      whatYouNeedToKnow: ["Place value tells the position of a digit.", "Value tells how much a digit is worth.", "Rounding helps estimate numbers quickly.", "Roman numerals use letters such as I, V, X and L."],
      worked: { problem: "Find the value of 8 in 384,216.", steps: ["Locate the digit 8.", "It is in the ten thousands place.", "Value = 8 × 10,000 = 80,000."], answer: "80,000" },
      commonMistakes: ["Confusing place value with value.", "Forgetting commas when reading large numbers.", "Rounding from the wrong digit."],
      recap: ["Read numbers in groups.", "Use place-value columns.", "Check the next digit when rounding."],
    },
    subtopics: [
      { subtopicId: "p5-place-value-six-digits", title: "1. Place value up to 999,999", modules: [{ moduleId: "p5-six-digit-place-value", title: "Six-Digit Numbers", bigIdea: "Digits become ten times larger as they move one place to the left.", learnIt: ["Place values include ones, tens, hundreds, thousands, ten thousands and hundred thousands.", "The value of a digit is digit times place value.", "Expanded form separates a number into the value of each digit."], workedExample: { question: "Write 425,306 in expanded form.", steps: ["4 is worth 400,000.", "2 is worth 20,000.", "5 is worth 5,000.", "3 is worth 300 and 6 is worth 6."], answer: "400,000 + 20,000 + 5,000 + 300 + 6" }, tryThis: { question: "What is the value of 7 in 572,914?", choices: ["70,000", "7,000", "700", "700,000"], correct: 0, explanation: "The 7 is in the ten thousands place." } }] },
      { subtopicId: "p5-rounding-roman", title: "2. Rounding and Roman numerals", modules: [{ moduleId: "p5-rounding-roman", title: "Rounding and Roman Numerals", bigIdea: "Rounding estimates values, while Roman numerals write numbers using letters.", learnIt: ["To round to the nearest 10,000, look at the thousands digit.", "If the next digit is 5 or more, round up; if less than 5, round down.", "Roman numerals up to 50 use I, V, X and L."], workedExample: { question: "Round 347,816 to the nearest ten thousand.", steps: ["The ten-thousands digit is 4.", "The thousands digit is 7.", "Since 7 is 5 or more, round up to 350,000."], answer: "350,000" }, tryThis: { question: "What is 40 in Roman numerals?", choices: ["XL", "XXXX", "LX", "VVVV"], correct: 0, explanation: "40 is written XL." } }] }
    ],
    quiz: [
      { q: "What is the value of 6 in 468,902?", choices: ["60,000", "6,000", "600", "600,000"], correct: 0, why: "6 is in the ten thousands place." },
      { q: "Round 82,415 to the nearest ten thousand.", choices: ["80,000", "82,000", "90,000", "100,000"], correct: 0, why: "The thousands digit is 2, so round down." },
      { q: "Which is the largest number?", choices: ["325,410", "324,999", "305,999", "320,999"], correct: 0, why: "325,410 has the greatest thousands value." },
      { q: "What is 50 in Roman numerals?", choices: ["L", "X", "V", "C"], correct: 0, why: "L represents 50." },
      { q: "Write 203,040 in words.", choices: ["Two hundred three thousand forty", "Twenty three thousand forty", "Two thousand thirty four", "Two hundred thirty thousand"], correct: 0, why: "203,040 is two hundred three thousand forty." },
      { q: "What is 90,000 + 4,000 + 50?", choices: ["94,050", "90,450", "94,500", "9,450"], correct: 0, why: "Add the values to get 94,050." },
    ],
  },
  {
    id: "p5-operations-whole-numbers",
    themeId: "p5-theme-numeracy",
    themeName: "Numeracy",
    title: "Operations on Whole Numbers",
    estMinutes: 32,
    status: "published",
    reviewStatus: "beta",
    note: { intro: `${BETA_NOTICE} Operations help learners solve problems about totals, differences, equal groups and sharing.`, learningObjectives: ["Add, subtract, multiply and divide whole numbers.", "Solve word problems using the correct operation."], whatYouNeedToKnow: ["Addition combines quantities.", "Subtraction finds what is left or the difference.", "Multiplication uses equal groups.", "Division shares or groups equally."], worked: { problem: "A shop sold 235 books on Monday and 184 books on Tuesday. How many books were sold altogether?", steps: ["Add Monday and Tuesday sales.", "235 + 184 = 419."], answer: "419 books." }, recap: ["Align place values.", "Choose the operation before calculating.", "Check if your answer is reasonable."] },
    subtopics: [{ subtopicId: "p5-four-operations", title: "1. Four operations", modules: [{ moduleId: "p5-operation-choice", title: "Choosing the Correct Operation", bigIdea: "The story in a word problem tells which operation is needed.", learnIt: ["Words like altogether often suggest addition.", "Words like left, difference or more than often suggest subtraction.", "Equal groups suggest multiplication or division."], workedExample: { question: "12 boxes each contain 18 pencils. How many pencils are there?", steps: ["Each box has the same number.", "Use multiplication: 12 × 18.", "12 × 18 = 216."], answer: "216 pencils" }, tryThis: { question: "A farmer shares 96 oranges equally among 8 baskets. Which operation is needed?", choices: ["Division", "Addition", "Subtraction", "Rounding"], correct: 0, explanation: "Sharing equally uses division." } }] }],
    quiz: [
      { q: "Find 4,816 + 2,309", choices: ["7,125", "6,125", "7,015", "2,507"], correct: 0, why: "Add in columns: 4,816 + 2,309 = 7,125." },
      { q: "Find 8,000 - 3,475", choices: ["4,525", "5,525", "4,625", "11,475"], correct: 0, why: "8,000 - 3,475 = 4,525." },
      { q: "Find 24 × 16", choices: ["384", "240", "264", "404"], correct: 0, why: "24 × 10 = 240 and 24 × 6 = 144; total = 384." },
      { q: "Find 144 ÷ 12", choices: ["12", "10", "14", "16"], correct: 0, why: "12 × 12 = 144." },
      { q: "A class has 38 boys and 42 girls. How many learners?", choices: ["80", "4", "70", "90"], correct: 0, why: "38 + 42 = 80." },
      { q: "A trader had 500 eggs and sold 175. How many remained?", choices: ["325", "675", "225", "375"], correct: 0, why: "500 - 175 = 325." },
    ],
  },
  {
    id: "p5-patterns-sequences",
    themeId: "p5-theme-numeracy",
    themeName: "Numeracy",
    title: "Patterns and Sequences",
    estMinutes: 25,
    status: "published",
    reviewStatus: "beta",
    note: { intro: `${BETA_NOTICE} Patterns help learners notice rules and predict the next numbers or shapes.`, learningObjectives: ["Identify number patterns.", "Find rules for sequences.", "Continue patterns correctly."], whatYouNeedToKnow: ["A sequence is an ordered list.", "A pattern has a rule.", "Rules may involve adding, subtracting, multiplying or alternating."], worked: { problem: "Find the next number: 4, 8, 12, 16, __", steps: ["Compare neighbouring numbers.", "Each number increases by 4.", "16 + 4 = 20."], answer: "20" }, recap: ["Look for the change between terms.", "Test the rule more than once.", "Use the rule to find missing terms."] },
    subtopics: [{ subtopicId: "p5-number-patterns", title: "1. Number patterns", modules: [{ moduleId: "p5-find-pattern-rule", title: "Finding the Rule", bigIdea: "A pattern rule explains how one term changes to the next.", learnIt: ["Check whether the pattern adds or subtracts the same number.", "If not, check multiplication, division or alternating rules.", "Write the rule before finding the missing term."], workedExample: { question: "Find the missing number: 3, 6, 12, 24, __", steps: ["3 × 2 = 6.", "6 × 2 = 12.", "12 × 2 = 24, so 24 × 2 = 48."], answer: "48" }, tryThis: { question: "What comes next: 50, 45, 40, 35, __?", choices: ["30", "25", "40", "32"], correct: 0, explanation: "The pattern subtracts 5 each time." } }] }],
    quiz: [
      { q: "What comes next: 2, 4, 6, 8, __?", choices: ["10", "9", "12", "6"], correct: 0, why: "The pattern adds 2." },
      { q: "What comes next: 5, 10, 20, 40, __?", choices: ["80", "60", "45", "100"], correct: 0, why: "Each term is multiplied by 2." },
      { q: "Find the missing number: 100, 90, 80, __, 60", choices: ["70", "75", "65", "50"], correct: 0, why: "The pattern subtracts 10." },
      { q: "Which sequence increases by 3?", choices: ["1, 4, 7, 10", "1, 3, 6, 10", "10, 7, 4, 1", "2, 4, 8, 16"], correct: 0, why: "Each term increases by 3." },
      { q: "What is the rule for 6, 12, 18, 24?", choices: ["Add 6", "Add 12", "Subtract 6", "Multiply by 6 each time"], correct: 0, why: "Each term is 6 more than the previous term." },
      { q: "What comes next: 1, 3, 6, 10, __?", choices: ["15", "14", "12", "20"], correct: 0, why: "The differences are +2, +3, +4, so next is +5." },
    ],
  },
  {
    id: "p5-fractions",
    themeId: "p5-theme-numeracy",
    themeName: "Numeracy",
    title: "Fractions",
    estMinutes: 30,
    status: "published",
    reviewStatus: "beta",
    note: { intro: `${BETA_NOTICE} Fractions and decimal fractions show parts of a whole and prepare learners for upper-primary calculations.`, learningObjectives: ["Understand tenths and hundredths.", "Order decimal fractions.", "Convert decimals to vulgar fractions.", "Add and subtract decimal fractions."], whatYouNeedToKnow: ["Tenths are one-digit decimal parts.", "Hundredths are two-digit decimal parts.", "Place value is important when adding and subtracting decimals."], worked: { problem: "Add 2.35 + 1.40.", steps: ["Line up decimal points.", "Add hundredths, tenths and ones.", "2.35 + 1.40 = 3.75."], answer: "3.75" }, recap: ["Line up decimal points.", "Read decimal place values from left to right after the point.", "Convert decimals using tenths or hundredths." ] },
    subtopics: [{ subtopicId: "p5-decimal-fractions", title: "1. Decimal fractions", modules: [{ moduleId: "p5-tenths-hundredths-decimals", title: "Tenths, Hundredths and Decimal Operations", bigIdea: "Decimals are fractions written using a decimal point.", learnIt: ["0.4 means four tenths or 4/10.", "0.25 means twenty-five hundredths or 25/100.", "When adding decimals, write decimal points under each other."], workedExample: { question: "Convert 0.6 to a vulgar fraction.", steps: ["0.6 means 6 tenths.", "Write 6/10.", "Simplify 6/10 to 3/5."], answer: "3/5" }, tryThis: { question: "What is 0.25 as a fraction?", choices: ["25/100", "25/10", "2/5", "1/25"], correct: 0, explanation: "0.25 means 25 hundredths." } }] }],
    quiz: [
      { q: "What is 0.7 as a fraction?", choices: ["7/10", "7/100", "70/10", "1/7"], correct: 0, why: "0.7 means seven tenths." },
      { q: "Add 1.25 + 2.30", choices: ["3.55", "3.45", "2.55", "4.55"], correct: 0, why: "Line up decimals: 1.25 + 2.30 = 3.55." },
      { q: "Subtract 5.80 - 2.40", choices: ["3.40", "3.20", "2.40", "4.20"], correct: 0, why: "5.80 - 2.40 = 3.40." },
      { q: "Which is greater: 0.6 or 0.45?", choices: ["0.6", "0.45", "They are equal", "Cannot tell"], correct: 0, why: "0.6 = 0.60, which is greater than 0.45." },
      { q: "Write 0.03 in words.", choices: ["three hundredths", "three tenths", "thirty tenths", "three wholes"], correct: 0, why: "0.03 has 3 in the hundredths place." },
      { q: "Arrange ascending: 0.5, 0.25, 0.75", choices: ["0.25, 0.5, 0.75", "0.75, 0.5, 0.25", "0.5, 0.25, 0.75", "0.25, 0.75, 0.5"], correct: 0, why: "0.25 is smallest, then 0.5, then 0.75." },
    ],
  },
  {
    id: "p5-lines-angles-geometrical-figures",
    themeId: "p5-theme-geometry",
    themeName: "Geometry",
    title: "Lines, Angles and Geometrical Figures",
    estMinutes: 35,
    status: "published",
    reviewStatus: "beta",
    note: { intro: `${BETA_NOTICE} Geometry helps learners draw, measure and describe shapes accurately.`, learningObjectives: ["Draw and identify parallel and perpendicular lines.", "Draw and measure angles.", "Construct circles and regular hexagons.", "Identify folding symmetry, rotations and revolutions."], whatYouNeedToKnow: ["Parallel lines never meet.", "Perpendicular lines meet at right angles.", "A circle is drawn using a compass.", "Symmetry means two matching halves."], worked: { problem: "Name two examples of parallel lines in a classroom.", steps: ["Look for lines that run in the same direction.", "Edges of a ruler are parallel.", "Opposite edges of a rectangular desk are parallel."], answer: "Edges of a ruler and opposite edges of a desk are examples." }, recap: ["Use a ruler and compass carefully.", "Right angles are 90 degrees.", "Symmetry creates matching halves." ] },
    subtopics: [{ subtopicId: "p5-lines-angles-shapes", title: "1. Lines, angles and shapes", modules: [{ moduleId: "p5-parallel-perpendicular-angles", title: "Parallel, Perpendicular and Angles", bigIdea: "Geometry starts with lines and angles drawn accurately.", learnIt: ["Parallel lines are always the same distance apart.", "Perpendicular lines meet at 90 degrees.", "Use a protractor to measure angles and a compass to draw circles."], workedExample: { question: "What is special about perpendicular lines?", steps: ["They meet each other.", "They form a right angle.", "A right angle is 90 degrees."], answer: "They meet at 90 degrees." }, tryThis: { question: "Parallel lines:", choices: ["do not meet", "always meet", "form a circle", "are always curved"], correct: 0, explanation: "Parallel lines do not meet." } }] }],
    quiz: [
      { q: "Parallel lines are lines that:", choices: ["do not meet", "meet at 90 degrees", "form circles", "are always short"], correct: 0, why: "Parallel lines never meet." },
      { q: "Perpendicular lines meet at:", choices: ["90 degrees", "45 degrees", "180 degrees", "360 degrees"], correct: 0, why: "Perpendicular lines form right angles." },
      { q: "Which instrument draws circles?", choices: ["Compass", "Ruler only", "Eraser", "Chalk box"], correct: 0, why: "A compass is used to draw circles." },
      { q: "A line of symmetry divides a shape into:", choices: ["two matching halves", "three unequal parts", "only circles", "no parts"], correct: 0, why: "Symmetry creates matching halves." },
      { q: "A complete revolution is:", choices: ["one full turn", "half a turn", "no turn", "a straight line"], correct: 0, why: "A revolution is a full turn around a point." },
      { q: "A regular hexagon has:", choices: ["6 equal sides", "5 equal sides", "4 sides", "3 sides"], correct: 0, why: "A hexagon has 6 sides; regular means all sides are equal." },
    ],
  },
  {
    id: "p5-data-handling",
    themeId: "p5-theme-graphs-data",
    themeName: "Interpretation of Graphs and Data",
    title: "Data Handling",
    estMinutes: 28,
    status: "published",
    reviewStatus: "beta",
    note: { intro: `${BETA_NOTICE} Graphs help learners present and interpret information clearly.`, learningObjectives: ["Read graph scales.", "Interpret bar and line graphs.", "Find averages from data."], whatYouNeedToKnow: ["Graphs have titles, labels and scales.", "Bar graphs compare amounts.", "Line graphs show changes.", "Average is total divided by number of items."], worked: { problem: "Find the average of 6, 8 and 10.", steps: ["Add the values: 6 + 8 + 10 = 24.", "There are 3 values.", "24 ÷ 3 = 8."], answer: "8" }, recap: ["Read the scale before answering.", "Use data to compare amounts.", "Average = total ÷ number of values." ] },
    subtopics: [{ subtopicId: "p5-graphs-average", title: "1. Graphs and average", modules: [{ moduleId: "p5-read-graphs-average", title: "Reading Graphs and Finding Average", bigIdea: "Data becomes useful when learners can read it and summarise it.", learnIt: ["A graph title tells what the graph is about.", "The vertical axis scale may count in 1s, 2s, 5s or 10s.", "Average is found by adding values and dividing by how many values there are."], workedExample: { question: "A graph shows 10 mangoes on Monday, 15 on Tuesday and 20 on Wednesday. Find the average.", steps: ["Add: 10 + 15 + 20 = 45.", "There are 3 days.", "45 ÷ 3 = 15."], answer: "15 mangoes." }, tryThis: { question: "Find the average of 4, 6 and 8.", choices: ["6", "18", "4", "8"], correct: 0, explanation: "4 + 6 + 8 = 18; 18 ÷ 3 = 6." } }] }],
    quiz: [
      { q: "A bar graph is mainly used to:", choices: ["compare amounts", "boil water", "show only prayers", "measure height directly"], correct: 0, why: "Bar graphs compare quantities." },
      { q: "Find the average of 5, 7 and 9.", choices: ["7", "21", "9", "5"], correct: 0, why: "5 + 7 + 9 = 21; 21 ÷ 3 = 7." },
      { q: "A graph scale counts by 5. The bar reaches the 6th mark. What value is it?", choices: ["30", "11", "6", "60"], correct: 0, why: "6 × 5 = 30." },
      { q: "A line graph is useful for showing:", choices: ["change over time", "only names", "only spelling", "only shapes"], correct: 0, why: "Line graphs show how values change." },
      { q: "Which should you read first on a graph?", choices: ["title", "shoe size", "last word only", "nothing"], correct: 0, why: "The title tells what the graph is about." },
      { q: "Find the total of 12, 8 and 10.", choices: ["30", "20", "24", "40"], correct: 0, why: "12 + 8 + 10 = 30." },
    ],
  },
  {
    id: "p5-time",
    themeId: "p5-theme-measurement",
    themeName: "Measurements",
    title: "Time",
    estMinutes: 28,
    status: "published",
    reviewStatus: "beta",
    note: { intro: `${BETA_NOTICE} Time helps learners read clocks, find duration and solve time-distance-speed problems.`, learningObjectives: ["Tell time on the 12-hour clock.", "Convert hours and minutes.", "Find duration.", "Solve simple time, distance and speed problems."], whatYouNeedToKnow: ["1 hour = 60 minutes.", "a.m. is before noon; p.m. is after noon.", "Duration is the time between a start and an end."], worked: { problem: "Find the duration from 8:30 a.m. to 10:00 a.m.", steps: ["8:30 to 9:30 is 1 hour.", "9:30 to 10:00 is 30 minutes."], answer: "1 hour 30 minutes." }, recap: ["Use 60 minutes in one hour.", "Count forward to find duration.", "Read a.m. and p.m. carefully." ] },
    subtopics: [{ subtopicId: "p5-time-duration-speed", title: "1. Time, duration and speed", modules: [{ moduleId: "p5-time-problems", title: "Practical Time Problems", bigIdea: "Time questions are easiest when learners count forward in steps.", learnIt: ["Use clock faces to practise minutes past and minutes to.", "Break duration into easy parts, such as to the next hour, then to the finish time.", "Speed, distance and time are related in simple travel problems."], workedExample: { question: "A journey begins at 2:15 p.m. and ends at 3:05 p.m. How long is it?", steps: ["2:15 to 3:00 = 45 minutes.", "3:00 to 3:05 = 5 minutes.", "Total = 50 minutes."], answer: "50 minutes" }, tryThis: { question: "How many minutes are in 3 hours?", choices: ["180", "120", "60", "300"], correct: 0, explanation: "3 × 60 = 180 minutes." } }] }],
    quiz: [
      { q: "How many minutes are in 2 hours?", choices: ["120", "60", "100", "200"], correct: 0, why: "2 × 60 = 120." },
      { q: "Find duration from 9:00 a.m. to 11:30 a.m.", choices: ["2 h 30 min", "1 h 30 min", "3 h", "30 min"], correct: 0, why: "9:00 to 11:00 is 2 hours, then 30 minutes." },
      { q: "Which comes after 11:59 a.m.?", choices: ["12:00 noon", "12:00 midnight", "10:00 a.m.", "1:00 a.m."], correct: 0, why: "After 11:59 a.m. comes 12:00 noon." },
      { q: "A car travels 60 km in 2 hours. What is its speed?", choices: ["30 km/h", "62 km/h", "120 km/h", "58 km/h"], correct: 0, why: "Speed = distance ÷ time = 60 ÷ 2 = 30 km/h." },
      { q: "What does p.m. mean?", choices: ["after noon", "before noon", "midnight only", "morning only"], correct: 0, why: "p.m. is used after noon." },
      { q: "How many seconds are in 1 minute?", choices: ["60", "100", "30", "24"], correct: 0, why: "1 minute = 60 seconds." },
    ],
  },
  {
    id: "p5-money",
    themeId: "p5-theme-measurement",
    themeName: "Measurements",
    title: "Money",
    estMinutes: 25,
    status: "published",
    reviewStatus: "beta",
    note: { intro: `${BETA_NOTICE} Money helps learners solve real-life buying, selling, profit and loss problems.`, learningObjectives: ["Use Uganda currency in calculations.", "Find cost, price and change.", "Compute simple profit and loss."], whatYouNeedToKnow: ["Cost price is buying price.", "Selling price is the price an item is sold for.", "Profit occurs when selling price is greater than cost price; loss occurs when selling price is less."], worked: { problem: "A trader buys a basket for UGX 8,000 and sells it for UGX 10,000. Find the profit.", steps: ["Profit = selling price - cost price.", "10,000 - 8,000 = 2,000."], answer: "UGX 2,000 profit." }, recap: ["Profit = SP - CP.", "Loss = CP - SP.", "Change = money paid - cost." ] },
    subtopics: [{ subtopicId: "p5-money-profit-loss", title: "1. Buying, selling, profit and loss", modules: [{ moduleId: "p5-money-market", title: "Market Money Problems", bigIdea: "Money maths becomes clear when learners identify cost price, selling price and change.", learnIt: ["Use UGX in money answers.", "If selling price is higher than cost price, there is profit.", "If selling price is lower than cost price, there is loss."], workedExample: { question: "A pencil costs UGX 700. A learner pays UGX 1,000. Find the change.", steps: ["Change = money paid - cost.", "1,000 - 700 = 300."], answer: "UGX 300" }, tryThis: { question: "A book bought at UGX 5,000 is sold at UGX 4,000. What happened?", choices: ["Loss of UGX 1,000", "Profit of UGX 1,000", "No change", "Profit of UGX 9,000"], correct: 0, explanation: "The selling price is lower than the cost price by UGX 1,000." } }] }],
    quiz: [
      { q: "A bag costs UGX 12,000. You pay UGX 20,000. Find the change.", choices: ["UGX 8,000", "UGX 32,000", "UGX 12,000", "UGX 2,000"], correct: 0, why: "20,000 - 12,000 = 8,000." },
      { q: "Cost price is:", choices: ["buying price", "selling price", "profit", "change"], correct: 0, why: "Cost price is the price at which something is bought." },
      { q: "Selling price is greater than cost price. This gives:", choices: ["profit", "loss", "debt", "change only"], correct: 0, why: "Profit occurs when SP > CP." },
      { q: "Find profit: CP = UGX 6,000, SP = UGX 7,500.", choices: ["UGX 1,500", "UGX 13,500", "UGX 500", "UGX 7,500"], correct: 0, why: "7,500 - 6,000 = 1,500." },
      { q: "Find loss: CP = UGX 9,000, SP = UGX 7,000.", choices: ["UGX 2,000", "UGX 16,000", "UGX 7,000", "UGX 9,000"], correct: 0, why: "9,000 - 7,000 = 2,000." },
      { q: "Which is Uganda currency?", choices: ["shilling", "dollar only", "pound only", "yen only"], correct: 0, why: "Uganda uses shillings." },
    ],
  },
  {
    id: "p5-length-mass-capacity",
    themeId: "p5-theme-measurement",
    themeName: "Measurements",
    title: "Length, Mass and Capacity",
    estMinutes: 32,
    status: "published",
    reviewStatus: "beta",
    note: { intro: `${BETA_NOTICE} Length, mass and capacity help learners measure accurately and solve practical problems.`, learningObjectives: ["Convert mm, cm and m.", "Find perimeter and area.", "Convert kg and g.", "Convert litres and millilitres."], whatYouNeedToKnow: ["10 mm = 1 cm and 100 cm = 1 m.", "1000 g = 1 kg.", "1000 ml = 1 litre.", "Perimeter is distance around; area is surface covered."], worked: { problem: "Convert 4 kg to grams.", steps: ["1 kg = 1000 g.", "4 × 1000 = 4000."], answer: "4000 g" }, recap: ["Write units.", "Use correct conversion facts.", "Area uses square units." ] },
    subtopics: [{ subtopicId: "p5-measurement-units", title: "1. Measuring length, mass and capacity", modules: [{ moduleId: "p5-conversions-area", title: "Conversions, Perimeter and Area", bigIdea: "Measurement problems need correct units before calculation.", learnIt: ["Convert metres to centimetres by multiplying by 100.", "Convert kilograms to grams by multiplying by 1000.", "Area of a rectangle = length × width."], workedExample: { question: "Find the area of a rectangle 8 cm long and 3 cm wide.", steps: ["Area = length × width.", "8 × 3 = 24."], answer: "24 cm²" }, tryThis: { question: "Convert 2 litres to millilitres.", choices: ["2000 ml", "200 ml", "20 ml", "2 ml"], correct: 0, explanation: "1 litre = 1000 ml." } }] }],
    quiz: [
      { q: "Convert 3 m to cm.", choices: ["300 cm", "30 cm", "3000 cm", "3 cm"], correct: 0, why: "1 m = 100 cm." },
      { q: "Convert 5 kg to grams.", choices: ["5000 g", "500 g", "50 g", "5 g"], correct: 0, why: "1 kg = 1000 g." },
      { q: "Convert 4 litres to ml.", choices: ["4000 ml", "400 ml", "40 ml", "4 ml"], correct: 0, why: "1 litre = 1000 ml." },
      { q: "Find the perimeter of a square of side 9 cm.", choices: ["36 cm", "18 cm", "81 cm", "27 cm"], correct: 0, why: "4 × 9 = 36 cm." },
      { q: "Find the area of a rectangle 7 cm by 5 cm.", choices: ["35 cm²", "24 cm²", "12 cm²", "30 cm²"], correct: 0, why: "7 × 5 = 35 cm²." },
      { q: "Which unit measures capacity?", choices: ["litre", "kilogram", "metre", "degree"], correct: 0, why: "Capacity is commonly measured in litres and millilitres." },
    ],
  },
  {
    id: "p5-integers",
    themeId: "p5-theme-numeracy",
    themeName: "Numeracy",
    title: "Integers",
    estMinutes: 24,
    status: "published",
    reviewStatus: "beta",
    note: { intro: `${BETA_NOTICE} Integers introduce learners to positive and negative numbers used in real-life situations.`, learningObjectives: ["Recognise positive and negative numbers.", "Order integers on a number line.", "Use integers in simple real-life contexts."], whatYouNeedToKnow: ["Positive numbers are greater than zero.", "Negative numbers are less than zero.", "A number further right on the number line is greater."], worked: { problem: "Which is greater: -2 or -6?", steps: ["Draw a number line.", "-2 is to the right of -6.", "The number to the right is greater."], answer: "-2 is greater." }, recap: ["Zero is neither positive nor negative.", "Negative numbers get smaller as they move left.", "Use number lines for comparison." ] },
    subtopics: [{ subtopicId: "p5-integer-number-line", title: "1. Integers on a number line", modules: [{ moduleId: "p5-positive-negative", title: "Positive and Negative Numbers", bigIdea: "Integers can show gains, losses, temperatures and positions around zero.", learnIt: ["Numbers above zero are positive.", "Numbers below zero are negative.", "Zero separates positive and negative numbers."], workedExample: { question: "Arrange -3, 2, 0 and -1 from smallest to greatest.", steps: ["Place them on a number line.", "Read from left to right."], answer: "-3, -1, 0, 2" }, tryThis: { question: "Which is smallest?", choices: ["-5", "-1", "0", "3"], correct: 0, explanation: "-5 is furthest left." } }] }],
    quiz: [
      { q: "Which number is negative?", choices: ["-4", "4", "0", "8"], correct: 0, why: "-4 is less than zero." },
      { q: "Which is greater: -1 or -5?", choices: ["-1", "-5", "They are equal", "Cannot tell"], correct: 0, why: "-1 is to the right of -5." },
      { q: "Arrange from smallest: -2, 0, 3", choices: ["-2, 0, 3", "3, 0, -2", "0, -2, 3", "-2, 3, 0"], correct: 0, why: "Numbers increase from left to right." },
      { q: "A temperature is 3 degrees below zero. It is written as:", choices: ["-3", "+3", "0", "30"], correct: 0, why: "Below zero is negative." },
      { q: "Zero is:", choices: ["neither positive nor negative", "always negative", "always positive", "less than all negatives"], correct: 0, why: "Zero separates positives and negatives." },
      { q: "Which number is furthest left on a number line?", choices: ["-7", "-2", "0", "1"], correct: 0, why: "-7 is smaller than -2, 0 and 1." },
    ],
  },
  {
    id: "p5-algebra",
    themeId: "p5-theme-algebra",
    themeName: "Algebra",
    title: "Algebra",
    estMinutes: 24,
    status: "published",
    reviewStatus: "beta",
    note: { intro: `${BETA_NOTICE} Algebra introduces unknown values and prepares learners for upper-primary equations.`, learningObjectives: ["Understand simple algebraic statements.", "Find unknown values.", "Solve simple equations."], whatYouNeedToKnow: ["A letter or box can stand for an unknown number.", "Use inverse operations to find the missing value.", "Check by putting the answer back into the number sentence."], worked: { problem: "Solve: x + 8 = 20.", steps: ["Subtract 8 from 20.", "20 - 8 = 12."], answer: "x = 12" }, recap: ["Unknowns can be letters or boxes.", "Undo the operation to find the unknown.", "Check your answer." ] },
    subtopics: [{ subtopicId: "p5-simple-equations", title: "1. Simple equations", modules: [{ moduleId: "p5-finding-unknown", title: "Finding Unknown Values", bigIdea: "A simple equation can be solved by undoing the operation.", learnIt: ["For x + 5 = 13, subtract 5 from 13.", "For x - 4 = 9, add 4 to 9.", "For 3 × x = 18, divide 18 by 3."], workedExample: { question: "Solve: 4 × y = 28.", steps: ["Undo multiplication by division.", "28 ÷ 4 = 7."], answer: "y = 7" }, tryThis: { question: "Solve: x - 6 = 10", choices: ["16", "4", "10", "6"], correct: 0, explanation: "Add 6 to both sides." } }] }],
    quiz: [
      { q: "Solve: x + 7 = 19", choices: ["12", "26", "7", "19"], correct: 0, why: "19 - 7 = 12." },
      { q: "Solve: y - 5 = 11", choices: ["16", "6", "55", "11"], correct: 0, why: "Add 5 to 11." },
      { q: "Solve: 3 × n = 21", choices: ["7", "18", "24", "63"], correct: 0, why: "21 ÷ 3 = 7." },
      { q: "A box plus 4 equals 13. What is the box?", choices: ["9", "17", "4", "13"], correct: 0, why: "13 - 4 = 9." },
      { q: "Which can represent an unknown number?", choices: ["x", "only 100", "a comma", "a full stop"], correct: 0, why: "A letter can stand for an unknown number." },
      { q: "Check x = 5 in x + 3 = 8.", choices: ["correct", "wrong", "cannot tell", "x is 8"], correct: 0, why: "5 + 3 = 8." },
    ],
  },
];

export function getP5MathTopic(id: string): Topic | undefined {
  return P5_MATH_TOPICS.find((topic) => topic.id === id);
}
