import type { ExerciseBlock, UpperPrimaryContentBlock, UpperPrimaryLesson } from "@/lib/content-blocks";
import type { Topic } from "@/lib/topics";

type ExerciseQuestion = ExerciseBlock["questions"][number];
type SubjectName = UpperPrimaryLesson["subject"];
type TermName = UpperPrimaryLesson["term"];

type LessonSpec = {
  id: string;
  term: TermName;
  subject: SubjectName;
  topicTitle: string;
  subTopicTitle: string;
  definition: string;
  simpleCheck?: string;
  categories: Array<{ name: string; definition: string; examples: string[]; notes?: string[] }>;
  examples: Array<{ name: string; explanation: string; localContext?: string }>;
  facts: string[];
  image?: { title: string; imageUrl: string; caption: string; labels?: string[] };
  worked?: { question: string; steps: string[]; answer: string };
  activity?: { title: string; instructions: string[]; safetyNote?: string };
  questions: ExerciseQuestion[];
};

const short = (prompt: string, answer?: string): ExerciseQuestion => ({ type: "short-answer", prompt, answer });
const written = (prompt: string, answer?: string): ExerciseQuestion => ({ type: "written", prompt, answer });
const mc = (prompt: string, choices: string[], answer: string): ExerciseQuestion => ({ type: "multiple-choice", prompt, choices, answer });
const cat = (name: string, definition: string, examples: string[], notes?: string[]) => ({ name, definition, examples, notes });
const ex = (name: string, explanation: string, localContext?: string) => ({ name, explanation, localContext });

function lesson(spec: LessonSpec): UpperPrimaryLesson {
  const blocks: UpperPrimaryContentBlock[] = [
    { kind: "definition", term: spec.subTopicTitle, definition: spec.definition, simpleCheck: spec.simpleCheck },
    { kind: "categories", title: "Types / key ideas", categories: spec.categories },
    { kind: "examples", title: "Examples and illustrations", examples: spec.examples },
    { kind: "characteristics", title: "Facts to remember", points: spec.facts },
  ];
  if (spec.image) blocks.push({ kind: "diagram", ...spec.image });
  if (spec.worked) blocks.push({ kind: "worked-example", ...spec.worked });
  if (spec.activity) blocks.push({ kind: "activity", ...spec.activity });
  blocks.push({ kind: "exercise", title: "Evaluation", questions: spec.questions });
  return {
    id: spec.id,
    classLevel: "P6",
    term: spec.term,
    curriculumMode: "subject",
    subject: spec.subject,
    topicTitle: spec.topicTitle,
    subTopicTitle: spec.subTopicTitle,
    lessonTitle: spec.subTopicTitle,
    blocks,
  };
}

function applyHeavyV4(topics: Topic[], overrides: Record<string, UpperPrimaryLesson[]>): Topic[] {
  return topics.map((topic) => {
    const upperPrimaryLessons = overrides[topic.id];
    if (!upperPrimaryLessons) return topic;
    return { ...topic, contentFormat: "upper-primary-v4" as const, upperPrimaryLessons, useOnlyV4Lessons: true };
  });
}

const P6_MATH_HEAVY_V4: Record<string, UpperPrimaryLesson[]> = {
  "p6-sets": [lesson({ id: "p6-math-sets-heavy-v4", term: "Term I", subject: "Mathematics", topicTitle: "Set Concepts up to Two Categories", subTopicTitle: "Sets, Venn Diagrams and Simple Probability", definition: "A set is a well-defined collection of different objects or numbers. P6 set work introduces listing members, comparing sets, using two-circle Venn diagrams and writing simple probability fractions.", simpleCheck: "Fill the Venn overlap first before filling the only-left and only-right regions.", categories: [cat("Equal set", "sets with exactly the same members", ["{2,4,6} and {6,4,2}"]), cat("Equivalent set", "sets with the same number of members", ["{a,b,c} and {1,2,3}"]), cat("Intersection", "members common to two sets", ["A ∩ B"]), cat("Probability", "chance of an event", ["favourable outcomes ÷ total outcomes"])], examples: [ex("Venn survey", "If 15 pupils like rice and 6 like both rice and posho, only rice is 15 - 6 = 9."), ex("Probability", "On a die, probability of an even number is 3/6 = 1/2."), ex("Subset", "{2,4} is a subset of {2,4,6,8}.")], facts: ["Use curly brackets when listing set members.", "Do not repeat members in a set.", "Intersection means common members.", "Probability is written as a fraction from 0 to 1."], image: { title: "Two-circle Venn diagram", imageUrl: "/images/math/venn-diagram-4-regions.png", caption: "Two-circle Venn diagrams sort members into only-left, overlap, only-right and neither.", labels: ["Only A", "A ∩ B", "Only B", "Neither"] }, worked: { question: "In a class of 40 pupils, 24 like mangoes, 18 like oranges and 10 like both. How many like neither?", steps: ["Overlap = 10.", "Only mangoes = 24 - 10 = 14.", "Only oranges = 18 - 10 = 8.", "At least one = 14 + 10 + 8 = 32.", "Neither = 40 - 32 = 8."], answer: "8 pupils" }, questions: [short("Define a set."), short("What does A ∩ B mean?", "Members common to A and B."), mc("Probability of a certain event is:", ["1", "0", "1/2", "2"], "1"), written("Draw a Venn diagram for 30 pupils where 16 like football, 12 like netball and 5 like both.")] })],
  "p6-whole-numbers": [lesson({ id: "p6-math-whole-numbers-heavy-v4", term: "Term I", subject: "Mathematics", topicTitle: "Whole Numbers up to 10,000,000", subTopicTitle: "Place Value, Roman Numerals and Base Five", definition: "Whole numbers are zero and counting numbers. P6 learners read and write whole numbers up to ten million, expand them, round them and work with Roman numerals and base five.", simpleCheck: "A digit's value changes when its place changes.", categories: [cat("Place value", "position of a digit", ["ones", "thousands", "millions"]), cat("Expanded form", "sum of place values", ["3,205 = 3000 + 200 + 5"]), cat("Roman numerals", "symbols for numbers", ["I", "V", "X", "L", "C", "D", "M"]), cat("Base five", "number system using digits 0 to 4", ["243₅"] )], examples: [ex("Reading", "6,048,215 is six million, forty-eight thousand, two hundred fifteen."), ex("Roman", "XL = 40 and IX = 9."), ex("Base five", "132₅ = 1×25 + 3×5 + 2 = 42." )], facts: ["Group large numbers in threes from the right.", "In base five, no digit should be 5 or more.", "Roman numeral symbols do not use place value.", "Rounding uses the digit to the right of the required place."], image: { title: "Place value chart", imageUrl: "/images/math/p4-place-value-chart.svg", caption: "Place value supports reading, writing and expanding large numbers.", labels: ["millions", "thousands", "ones"] }, worked: { question: "Write 4,708,036 in expanded form.", steps: ["4 is in millions: 4,000,000.", "7 is in hundred thousands: 700,000.", "8 is in thousands: 8,000.", "3 is in tens: 30; 6 is ones: 6."], answer: "4,000,000 + 700,000 + 8,000 + 30 + 6" }, questions: [short("What is the value of 7 in 4,708,036?", "700,000"), short("Which digits are allowed in base five?", "0, 1, 2, 3, 4"), mc("L in Roman numerals means:", ["50", "100", "500", "10"], "50"), written("Round 8,496 to the nearest hundred.", "8,500")] })],
  "p6-operations": [lesson({ id: "p6-math-operations-heavy-v4", term: "Term I", subject: "Mathematics", topicTitle: "Operations on Whole Numbers", subTopicTitle: "Operations, BODMAS, Prime Factors, GCF and LCM", definition: "Operations on whole numbers use addition, subtraction, multiplication and division to solve numerical and word problems. P6 also uses BODMAS, prime factorisation, GCF and LCM.", simpleCheck: "Use BODMAS when more than one operation appears in a question.", categories: [cat("BODMAS", "order of operations", ["brackets", "orders", "division/multiplication", "addition/subtraction"]), cat("Prime factor", "prime number that divides a number exactly", ["2 and 3 are prime factors of 12"]), cat("GCF", "greatest common factor", ["largest equal group"]), cat("LCM", "lowest common multiple", ["first common meeting point"] )], examples: [ex("BODMAS", "4 + 3 × 5 = 19."), ex("Prime factors", "24 = 2 × 2 × 2 × 3."), ex("LCM", "LCM of 4 and 6 is 12." )], facts: ["Multiplication is done before addition unless brackets change the order.", "Use GCF for sharing into equal groups.", "Use LCM for repeated events.", "Check word problems for key ideas such as altogether, left, each, shared and difference."], image: { title: "Four operations", imageUrl: "/images/math/p4-four-operations.svg", caption: "The four operations are used throughout upper-primary mathematics.", labels: ["+", "−", "×", "÷"] }, worked: { question: "Simplify 30 - 2(4 + 5).", steps: ["Brackets: 4 + 5 = 9.", "Multiplication: 2 × 9 = 18.", "Subtraction: 30 - 18 = 12."], answer: "12" }, questions: [short("What does GCF mean?", "Greatest Common Factor."), short("Find the LCM of 3 and 5.", "15"), mc("In BODMAS, brackets are done:", ["first", "last", "after addition", "never"], "first"), written("Find the prime factors of 36.", "2 × 2 × 3 × 3")] })],
  "p6-fractions-decimals": [lesson({ id: "p6-math-fractions-decimals-heavy-v4", term: "Term II", subject: "Mathematics", topicTitle: "Fractions, Decimals and Percentages", subTopicTitle: "Fractions, Decimals, Ratios and Percentages", definition: "Fractions, decimals and percentages are ways of showing parts of a whole. P6 learners operate on fractions, convert decimals and solve simple ratio, proportion and percentage problems.", simpleCheck: "Percent means out of 100.", categories: [cat("Fraction", "part of a whole", ["3/4"]), cat("Decimal", "number with a decimal point", ["0.75"]), cat("Percentage", "fraction out of 100", ["75%"]), cat("Ratio", "comparison of quantities", ["2:3"] )], examples: [ex("Fraction to decimal", "1/4 = 0.25."), ex("Percentage", "20% of 500 = 100."), ex("Ratio", "If boys:girls = 2:3, there are 5 total parts." )], facts: ["Find common denominators before adding unlike fractions.", "Convert mixed numbers to improper fractions before multiplying.", "To find a percentage of a number, write the percentage over 100 and multiply.", "Ratios must compare quantities in the same units."], image: { title: "Fraction strips", imageUrl: "/images/math/fraction-strips.svg", caption: "Fraction strips help compare parts of a whole.", labels: ["whole", "halves", "quarters"] }, worked: { question: "Find 15% of 800.", steps: ["Write 15% as 15/100.", "15/100 × 800.", "800 ÷ 100 = 8.", "15 × 8 = 120."], answer: "120" }, questions: [short("What does percent mean?", "Out of 100."), short("Change 0.5 to a percentage.", "50%"), mc("1/2 is equal to:", ["50%", "25%", "75%", "10%"], "50%"), written("Work out 2/3 + 1/6.", "5/6")] })],
  "p6-geometry": [lesson({ id: "p6-math-geometry-heavy-v4", term: "Term II", subject: "Mathematics", topicTitle: "Geometry and Angle Properties", subTopicTitle: "Angles, Construction, Perimeter and Area", definition: "Geometry studies shapes, lines, angles and space. P6 learners identify angle properties, construct common angles and calculate perimeter and area of simple shapes.", simpleCheck: "Angles on a straight line add up to 180 degrees.", categories: [cat("Acute angle", "less than 90°", ["35°"]), cat("Right angle", "exactly 90°", ["corner of a square"]), cat("Obtuse angle", "more than 90° but less than 180°", ["120°"]), cat("Area", "surface covered by a shape", ["cm²", "m²"] )], examples: [ex("Straight line", "If one angle is 65° on a straight line, the other is 115°."), ex("Rectangle area", "Area = length × width."), ex("Triangle area", "Area = 1/2 × base × height." )], facts: ["Use ruler and compasses for accurate construction.", "Perimeter is distance around a shape.", "Area uses square units.", "Parallel lines never meet."], image: { title: "Angle types", imageUrl: "/images/math/angle-types-gallery.png", caption: "Angle types help learners solve geometry questions.", labels: ["acute", "right", "obtuse", "straight"] }, worked: { question: "Find the area of a triangle with base 10 cm and height 8 cm.", steps: ["Area = 1/2 × base × height.", "Area = 1/2 × 10 × 8.", "10 × 8 = 80; half of 80 is 40."], answer: "40 cm²" }, questions: [short("How many degrees are on a straight line?", "180°"), short("Define perimeter."), mc("An angle of 120° is:", ["obtuse", "acute", "right", "zero"], "obtuse"), written("Find the area of a rectangle 12 cm by 7 cm.", "84 cm²")] })],
  "p6-data-algebra": [lesson({ id: "p6-math-data-algebra-heavy-v4", term: "Term III", subject: "Mathematics", topicTitle: "Data Handling and Simple Algebra", subTopicTitle: "Graphs, Averages and Simple Equations", definition: "Data handling organises information using tables, graphs and averages. Algebra uses letters to represent unknown numbers and solve equations.", simpleCheck: "Arrange numbers in order before finding the median.", categories: [cat("Bar graph", "uses bars to compare data", ["class favourite fruits"]), cat("Line graph", "shows continuous change", ["temperature over time"]), cat("Mean", "sum divided by number of values", ["average mark"]), cat("Equation", "mathematical sentence with an equal sign", ["x + 5 = 12"] )], examples: [ex("Mean", "Mean of 3, 5, 7 = 15 ÷ 3 = 5."), ex("Mode", "Mode of 2, 4, 4, 5 is 4."), ex("Equation", "p/4 = 5 gives p = 20." )], facts: ["Read graph title, scale and labels before answering.", "Median is the middle value after ordering.", "Range is largest minus smallest.", "Use inverse operations to solve equations."], image: { title: "Data graphs", imageUrl: "/images/math/p5-data-bar-line-graphs.svg", caption: "Graphs help present and interpret data.", labels: ["bar graph", "line graph", "scale"] }, worked: { question: "Solve p/4 = 5.", steps: ["p is divided by 4.", "Use the inverse operation: multiply both sides by 4.", "p = 5 × 4 = 20."], answer: "p = 20" }, questions: [short("Define mean."), short("Find the range of 4, 9, 2, 12.", "10"), mc("The most common value is the:", ["mode", "mean", "range", "scale"], "mode"), written("Solve x + 8 = 19.", "x = 11")] })],
};

const P6_SCIENCE_HEAVY_V4: Record<string, UpperPrimaryLesson[]> = {
  "p6-classification-living-things": [lesson({ id: "p6-science-classification-heavy-v4", term: "Term I", subject: "Integrated Science", topicTitle: "Classification of Living Things", subTopicTitle: "Classification of Plants and Animals", definition: "Classification is the grouping of living things according to shared characteristics. It helps learners identify plants and animals accurately.", simpleCheck: "Living things are grouped by observable features such as body covering, backbone, habitat and reproduction.", categories: [cat("Vertebrates", "animals with backbones", ["fish", "amphibians", "reptiles", "birds", "mammals"]), cat("Invertebrates", "animals without backbones", ["insects", "worms", "snails"]), cat("Flowering plants", "plants that produce flowers and seeds", ["beans", "maize", "mango"]), cat("Non-flowering plants", "plants that do not produce flowers", ["ferns", "mosses"] )], examples: [ex("Mammal", "A cow has hair, gives birth and suckles young ones."), ex("Bird", "A hen has feathers, wings and lays eggs."), ex("Insect", "A grasshopper has three body parts and six legs." )], facts: ["Classification makes study and identification easier.", "Vertebrates have internal skeletons with backbones.", "Insects have head, thorax, abdomen and six legs.", "Plants can also be grouped by roots, stems, leaves, flowers and seeds."], image: { title: "Flowering plant parts", imageUrl: "/images/science/flowering-plant-parts.svg", caption: "Plant parts help learners classify and describe plants.", labels: ["root", "stem", "leaf", "flower"] }, questions: [short("Define classification."), short("Name the five groups of vertebrates."), mc("An animal without a backbone is:", ["invertebrate", "mammal", "bird", "reptile"], "invertebrate"), written("Give three characteristics of insects.")] })],
  "p6-sound-energy": [lesson({ id: "p6-science-sound-heavy-v4", term: "Term I", subject: "Integrated Science", topicTitle: "Sound Energy and the Human Ear", subTopicTitle: "Sound, Vibrations and Hearing", definition: "Sound is a form of energy produced by vibrating objects. It travels through solids, liquids and gases and is detected by the ear.", simpleCheck: "Sound cannot travel through a vacuum because it needs a material medium.", categories: [cat("Source of sound", "object that vibrates to produce sound", ["drum skin", "vocal cords", "bell"]), cat("Pitch", "how high or low a sound is", ["whistle is high pitch"]), cat("Loudness", "how strong or soft a sound is", ["shouting is loud"]), cat("Ear", "organ used for hearing", ["outer ear", "middle ear", "inner ear"] )], examples: [ex("Vibration", "A plucked guitar string vibrates and produces sound."), ex("Echo", "Sound reflected from a hard surface may return as an echo."), ex("Ear care", "Avoid inserting sharp objects into the ear." )], facts: ["Sound travels fastest in solids and slower in gases.", "The eardrum vibrates when sound reaches it.", "Very loud sound can damage hearing.", "The ear also helps with balance."], activity: { title: "Sound observation", instructions: ["Touch your throat gently while speaking.", "Feel the vibration of vocal cords.", "Explain why vibration is needed for sound."], safetyNote: "Do not shout near someone's ear." }, questions: [short("What produces sound?", "Vibrating objects."), short("Name the part of the ear that vibrates first inside the ear canal.", "Eardrum."), mc("Sound travels fastest through:", ["solids", "air", "vacuum", "empty space"], "solids"), written("Give three ways of caring for the ears.")] })],
  "p6-circulatory-system": [lesson({ id: "p6-science-circulatory-heavy-v4", term: "Term II", subject: "Integrated Science", topicTitle: "The Human Circulatory System", subTopicTitle: "Heart, Blood and Blood Vessels", definition: "The circulatory system transports blood around the body. It is made up of the heart, blood and blood vessels.", simpleCheck: "The heart pumps blood; blood vessels carry blood; blood transports materials.", categories: [cat("Heart", "muscular organ that pumps blood", ["left and right sides"]), cat("Arteries", "blood vessels carrying blood away from the heart", ["aorta"]), cat("Veins", "blood vessels carrying blood back to the heart", ["vena cava"]), cat("Capillaries", "tiny vessels where exchange occurs", ["oxygen and nutrients move to cells"] )], examples: [ex("Red blood cells", "Carry oxygen using haemoglobin."), ex("White blood cells", "Help fight germs."), ex("Platelets", "Help blood clot after injury." )], facts: ["Blood plasma carries dissolved substances.", "Exercise strengthens the heart.", "A balanced diet supports healthy blood.", "Avoid smoking and too much fatty food to protect the circulatory system."], questions: [short("Name the organ that pumps blood.", "Heart."), short("Which blood cells carry oxygen?", "Red blood cells."), mc("Blood vessels that carry blood away from the heart are:", ["arteries", "veins", "capillaries", "nerves"], "arteries"), written("Give three ways of caring for the circulatory system.")] })],
  "p6-respiratory-system": [lesson({ id: "p6-science-respiratory-heavy-v4", term: "Term II", subject: "Integrated Science", topicTitle: "The Human Respiratory System", subTopicTitle: "Breathing and Gas Exchange", definition: "The respiratory system helps the body take in oxygen and remove carbon dioxide. It includes the nose, windpipe, bronchi, lungs and diaphragm.", simpleCheck: "Inhaled air has more oxygen; exhaled air has more carbon dioxide and water vapour.", categories: [cat("Inhalation", "breathing in air", ["diaphragm contracts", "chest expands"]), cat("Exhalation", "breathing out air", ["diaphragm relaxes", "chest falls"]), cat("Gas exchange", "movement of oxygen into blood and carbon dioxide out of blood", ["air sacs/alveoli"]), cat("Respiratory disease", "disease affecting breathing organs", ["asthma", "pneumonia", "tuberculosis"] )], examples: [ex("Nose", "Filters, warms and moistens air."), ex("Lungs", "Contain air sacs where gas exchange occurs."), ex("Exercise", "Breathing rate increases to supply more oxygen." )], facts: ["Do not breathe through dusty or smoky air when avoidable.", "Cover the mouth when coughing or sneezing.", "Good ventilation reduces spread of respiratory disease.", "Smoking damages lungs."], questions: [short("Name two organs in the respiratory system."), short("Which gas is needed by body cells for respiration?", "Oxygen."), mc("The diaphragm mainly helps in:", ["breathing", "chewing", "seeing", "hearing"], "breathing"), written("Give three ways of caring for the respiratory system.")] })],
  "p6-livestock-keeping": [lesson({ id: "p6-science-livestock-heavy-v4", term: "Term III", subject: "Integrated Science", topicTitle: "Cattle and Poultry Keeping", subTopicTitle: "Cattle, Poultry, Breeds, Care and Diseases", definition: "Livestock keeping is the rearing of domestic animals such as cattle and poultry for food, income and other products.", simpleCheck: "Good housing, feeding, hygiene and disease control improve animal production.", categories: [cat("Cattle", "large domestic animals kept for milk, meat, hides, manure and draught power", ["local", "exotic", "cross-breeds"]), cat("Poultry", "domestic birds kept for eggs, meat or feathers", ["chicken", "ducks", "turkeys"]), cat("Animal disease", "illness affecting livestock", ["East Coast Fever", "Newcastle disease", "coccidiosis"]), cat("Animal product", "useful material obtained from livestock", ["milk", "eggs", "meat", "manure"] )], examples: [ex("Dairy cattle", "Kept mainly for milk."), ex("Layers", "Poultry kept mainly for egg production."), ex("Vaccination", "Protects animals from some dangerous diseases." )], facts: ["Clean housing reduces parasites and disease.", "Balanced feeds support growth and production.", "Isolate sick animals to reduce spread of disease.", "Veterinary advice is important when treating livestock."], image: { title: "Poultry and bees", imageUrl: "/images/science/p5-poultry-bees.svg", caption: "Good animal care supports food and income at home and in the community.", labels: ["housing", "feeding", "health", "products"] }, questions: [short("Define poultry."), short("Give two products from cattle."), mc("Newcastle disease mainly affects:", ["poultry", "maize", "fish", "beans"], "poultry"), written("Give four ways of caring for livestock.")] })],
};

const P6_ENGLISH_HEAVY_V4: Record<string, UpperPrimaryLesson[]> = {
  "p6-safety-road": [lesson({ id: "p6-english-road-safety-heavy-v4", term: "Term I", subject: "English", topicTitle: "Safety on the Road", subTopicTitle: "Road Safety Vocabulary, Instructions and Advice", definition: "Road safety means using roads carefully to prevent accidents. In English, learners practise vocabulary, instructions, warnings and advice about safe road use.", simpleCheck: "Use must, should and should not to give safety advice.", categories: [cat("Road user", "person using the road", ["pedestrian", "cyclist", "driver", "passenger"]), cat("Road sign", "symbol or notice giving road information", ["Stop", "school ahead", "zebra crossing"]), cat("Instruction", "sentence telling someone what to do", ["Look right, left and right again."] )], examples: [ex("Advice", "Pedestrians should use the zebra crossing."), ex("Warning", "Do not play near the road."), ex("Instruction", "Fasten your seat belt before the vehicle starts." )], facts: ["Imperative sentences can give instructions.", "Polite advice can use should or ought to.", "Road safety composition should include causes, effects and prevention of accidents.", "Use clear sequencing when describing how to cross a road."], questions: [short("Who is a pedestrian?", "A person walking on or near a road."), short("Give two road users."), mc("Which word gives strong advice?", ["must", "yesterday", "under", "slowly"], "must"), written("Write three road safety rules for pupils.")] })],
  "p6-debating": [lesson({ id: "p6-english-debating-heavy-v4", term: "Term I", subject: "English", topicTitle: "Debating and Expressing Opinions", subTopicTitle: "Debating, Opinions and Reasons", definition: "Debating is a formal discussion where speakers support or oppose a motion. It helps learners express opinions clearly and give reasons respectfully.", simpleCheck: "A strong opinion needs a reason and an example.", categories: [cat("Motion", "topic being debated", ["Boarding school is better than day school"]), cat("Proposer", "speaker supporting the motion", ["first proposer"]), cat("Opposer", "speaker against the motion", ["first opposer"]), cat("Rebuttal", "answer to the other side's point", ["I disagree because..."] )], examples: [ex("Opinion", "In my opinion, school gardens are useful because they provide food."), ex("Agreement", "I support the previous speaker's point."), ex("Disagreement", "I respectfully disagree with that view because..." )], facts: ["Use polite debate language, not insults.", "Start with greeting the chairperson, judges and audience.", "Use linking words: firstly, secondly, finally.", "End by restating your position."], questions: [short("What is a motion in debating?"), short("Name one polite phrase for disagreement."), mc("A person who supports the motion is a:", ["proposer", "opposer", "timekeeper only", "audience"], "proposer"), written("Write one argument supporting school cleanliness.")] })],
  "p6-family-relationships": [lesson({ id: "p6-english-family-relationships-heavy-v4", term: "Term II", subject: "English", topicTitle: "Family Relationships", subTopicTitle: "Family Vocabulary, Respectful Speech and Letter Writing", definition: "Family relationships are connections among people in a family. This topic builds vocabulary for relatives, duties, respect, invitations, messages and family letters.", simpleCheck: "Use respectful language when speaking or writing to family members.", categories: [cat("Nuclear family", "parents and their children", ["father, mother and children"]), cat("Extended family", "relatives beyond parents and children", ["grandparents", "uncles", "aunts", "cousins"]), cat("Responsibility", "duty performed by a family member", ["helping with chores", "caring for young ones"] )], examples: [ex("Request", "Please allow me to visit grandmother during the holiday."), ex("Appreciation", "Thank you for paying my school fees."), ex("Family duty", "Children should help with safe age-appropriate work at home." )], facts: ["Use capital letters for proper names.", "A family letter should have a friendly tone.", "Use pronouns clearly to avoid confusion.", "Respectful speech strengthens family relationships."], questions: [short("Define extended family."), short("Name two members of an extended family."), mc("A father's brother is your:", ["uncle", "cousin", "niece", "grandmother"], "uncle"), written("Write four sentences thanking a guardian for helping you.")] })],
  "p6-occupations-crafts": [lesson({ id: "p6-english-occupations-crafts-heavy-v4", term: "Term II", subject: "English", topicTitle: "Occupations and Crafts", subTopicTitle: "Occupations, Tools, Crafts and Descriptions", definition: "An occupation is work a person does to earn a living or serve the community. A craft is skilled work done by hand to make useful or decorative items.", simpleCheck: "Describe a job by naming the worker, place of work, tools and service provided.", categories: [cat("Occupation", "regular work", ["teacher", "nurse", "carpenter", "farmer"]), cat("Craft", "hand skill used to make things", ["basket weaving", "pottery", "tailoring"]), cat("Tool", "object used to do work", ["hammer", "needle", "hoe"] )], examples: [ex("Carpenter", "A carpenter uses a saw, hammer and plane to make furniture."), ex("Nurse", "A nurse cares for sick people in a clinic or hospital."), ex("Basket weaver", "A basket weaver uses fibres to make baskets and mats." )], facts: ["Use present simple tense to describe daily work.", "Use adjectives to describe products: strong, neat, smooth, colourful.", "Occupations provide goods, services and income.", "Respect all honest work."], questions: [short("What is an occupation?"), short("Name two crafts."), mc("A person who makes furniture is a:", ["carpenter", "pilot", "doctor", "fisherman"], "carpenter"), written("Describe the work of a farmer in four sentences.")] })],
  "p6-hotel-dining": [lesson({ id: "p6-english-hotel-dining-heavy-v4", term: "Term III", subject: "English", topicTitle: "Hotel and Dining Etiquette", subTopicTitle: "Hotel Vocabulary, Ordering Food and Table Manners", definition: "Hotel and dining etiquette means polite behaviour when eating, ordering food or receiving service in a hotel, restaurant or home setting.", simpleCheck: "Use polite expressions such as please, may I and thank you.", categories: [cat("Menu", "list of food and drinks available", ["breakfast menu", "lunch menu"]), cat("Waiter/waitress", "person who serves food and drinks", ["restaurant staff"]), cat("Beverage", "drink other than plain water", ["tea", "juice", "soda"]), cat("Table manners", "polite rules while eating", ["do not talk with food in the mouth"] )], examples: [ex("Ordering", "May I have rice and chicken, please?"), ex("Request", "Could you bring the bill, please?"), ex("Manners", "Wash hands before eating and use cutlery properly." )], facts: ["Use a little for uncountable nouns like salt, soup and water.", "Use a few for countable nouns like plates, guests and chairs.", "Polite dialogue uses greeting, request, response and thanks.", "Hotel vocabulary includes guest, receptionist, reservation, bill and waiter."], questions: [short("What is a menu?"), short("Give two polite words used when ordering food."), mc("Which phrase is polite?", ["May I have tea, please?", "Give me now!", "You there!", "Move!"], "May I have tea, please?"), written("Write a short dialogue between a guest and a waiter.")] })],
};

const P6_SOCIAL_HEAVY_V4: Record<string, UpperPrimaryLesson[]> = {
  "p6-location-east-africa": [lesson({ id: "p6-sst-location-east-africa-heavy-v4", term: "Term I", subject: "Social Studies", topicTitle: "Location of East Africa on the Map of Africa", subTopicTitle: "Location, Countries and Map Skills of East Africa", definition: "Location means the position of a place. East Africa is a region in Africa made up of countries that cooperate through history, trade, transport and regional organisations.", simpleCheck: "Uganda is a landlocked country in East Africa.", categories: [cat("Absolute location", "position using latitudes and longitudes", ["Equator", "Tropic lines"]), cat("Relative location", "position described using nearby places", ["Uganda lies west of Kenya"]), cat("Landlocked country", "country without a coastline", ["Uganda", "Rwanda", "Burundi"] )], examples: [ex("Neighbour", "Kenya lies to the east of Uganda."), ex("Water body", "Lake Victoria is shared by Uganda, Kenya and Tanzania."), ex("Map element", "A key explains symbols used on a map." )], facts: ["The Equator crosses East Africa.", "East Africa borders the Indian Ocean to the east.", "Map skills require title, key, scale and compass direction.", "Regional location supports trade, transport and cooperation."], image: { title: "Uganda in East Africa", imageUrl: "/images/social-studies/p5-uganda-east-africa-map.svg", caption: "Uganda is part of the East African region.", labels: ["Uganda", "Kenya", "Tanzania", "Lake Victoria"] }, questions: [short("Define location."), short("Name two landlocked countries in East Africa."), mc("The ocean east of East Africa is the:", ["Indian Ocean", "Atlantic Ocean", "Arctic Ocean", "Pacific Ocean"], "Indian Ocean"), written("Give four elements of a good map.")] })],
  "p6-physical-features-ea": [lesson({ id: "p6-sst-physical-features-east-africa-heavy-v4", term: "Term I", subject: "Social Studies", topicTitle: "Physical Features of East Africa", subTopicTitle: "Mountains, Lakes, Rivers and Rift Valley of East Africa", definition: "Physical features are natural features on the earth's surface. East Africa has mountains, plateaus, lakes, rivers, valleys and plains.", simpleCheck: "Physical features influence climate, settlement, transport and economic activities.", categories: [cat("Mountain", "high land rising above surrounding land", ["Rwenzori", "Kilimanjaro", "Kenya"]), cat("Lake", "large body of water surrounded by land", ["Victoria", "Tanganyika", "Albert"]), cat("River", "flowing body of water", ["Nile", "Kagera"]), cat("Rift Valley", "long valley formed by faulting", ["Western and Eastern Rift Valley branches"] )], examples: [ex("Mount Kilimanjaro", "Highest mountain in Africa, found in Tanzania."), ex("Lake Victoria", "Largest lake in Africa and shared by Uganda, Kenya and Tanzania."), ex("River Nile", "Important river flowing from the Lake Victoria region northwards." )], facts: ["Highlands can receive relief rainfall.", "Lakes support fishing, transport and tourism.", "Rift valley features include escarpments, lakes and volcanoes.", "Conservation protects physical features from pollution and misuse."], image: { title: "Major rivers and lakes", imageUrl: "/images/social-studies/major-rivers-lakes-map.png", caption: "Water features support many human activities in East Africa and Africa.", labels: ["Lake Victoria", "Nile", "Tanganyika"] }, questions: [short("Define a physical feature."), short("Name the highest mountain in Africa.", "Mount Kilimanjaro."), mc("Lake Victoria is shared by Uganda, Kenya and:", ["Tanzania", "Egypt", "Nigeria", "Morocco"], "Tanzania"), written("Give three uses of lakes in East Africa.")] })],
  "p6-climate-vegetation-ea": [lesson({ id: "p6-sst-climate-vegetation-east-africa-heavy-v4", term: "Term I", subject: "Social Studies", topicTitle: "Climate and Natural Vegetation of East Africa", subTopicTitle: "Climate, Vegetation and Human Activities", definition: "Climate is the average weather of a place over a long time. Natural vegetation is plant cover that grows without being planted by people. In East Africa, climate and vegetation influence farming, settlement and wildlife.", simpleCheck: "Altitude, latitude, winds, distance from water bodies and relief affect climate.", categories: [cat("Equatorial climate", "hot and wet most of the year", ["areas near Lake Victoria"]), cat("Savanna vegetation", "grassland with scattered trees", ["many wildlife areas"]), cat("Mountain vegetation", "plant cover changing with altitude", ["forest", "bamboo", "moorland"]), cat("Semi-arid vegetation", "dry grass and thorny bushes", ["parts of north-eastern Kenya"] )], examples: [ex("Relief rainfall", "Moist air rises over highlands, cools and forms rain."), ex("Savanna", "Supports pastoralism and wildlife tourism."), ex("Forest", "Protects soil, supports rainfall and provides habitats." )], facts: ["Highland areas are cooler than lowlands.", "Vegetation is affected by rainfall and temperature.", "Deforestation can lead to soil erosion and reduced rainfall reliability.", "Climate affects crops grown in different areas."], image: { title: "Relief rainfall", imageUrl: "/images/social-studies/relief-orographic-rainfall.png", caption: "Relief rainfall forms when moist air rises over highlands.", labels: ["moist wind", "mountain", "rain", "rain shadow"] }, questions: [short("Define climate."), short("Name two factors affecting climate."), mc("Savanna vegetation is mainly:", ["grass with scattered trees", "ice sheet", "bare rock only", "seaweed"], "grass with scattered trees"), written("Explain how vegetation helps protect soil.")] })],
  "p6-people-precolonial-ea": [lesson({ id: "p6-sst-people-precolonial-east-africa-heavy-v4", term: "Term II", subject: "Social Studies", topicTitle: "The People and Pre-Colonial History of East Africa", subTopicTitle: "People, Migration, Kingdoms and Ways of Life", definition: "Pre-colonial history refers to the period before European colonial rule. East African societies had migrations, kingdoms, chiefdoms, clans, trade, farming, pastoralism and cultures.", simpleCheck: "East African people had organised political, social and economic systems before colonial rule.", categories: [cat("Bantu", "people speaking related Bantu languages", ["Baganda", "Basoga", "Chagga", "Kikuyu"]), cat("Nilotes", "people linked to Nile Valley migrations", ["Luo", "Acholi", "Maasai"]), cat("Kingdom", "state ruled by a king", ["Buganda", "Bunyoro"]), cat("Long-distance trade", "trade over long routes", ["salt", "iron tools", "ivory", "cloth"] )], examples: [ex("Migration", "People moved to search for fertile land, pasture, water, trade and security."), ex("Culture", "Language, food, dress, music and customs identify communities."), ex("Iron working", "Iron tools improved farming and defence." )], facts: ["Pre-colonial leaders included kings, chiefs and clan heads.", "Trade linked inland communities with coastal traders.", "Pastoralists moved with animals in search of pasture and water.", "Studying pre-colonial history shows that African societies were organised."], questions: [short("What does pre-colonial mean?"), short("Name two reasons why people migrated."), mc("A state ruled by a king is a:", ["kingdom", "desert", "river", "school"], "kingdom"), written("Give three economic activities of pre-colonial East African societies.")] })],
  "p6-colonization-ea": [lesson({ id: "p6-sst-colonization-east-africa-heavy-v4", term: "Term II", subject: "Social Studies", topicTitle: "Foreign Influence and Colonization of East Africa", subTopicTitle: "Foreign Influence, Scramble and Colonial Rule", definition: "Foreign influence refers to effects of outsiders on East Africa. Colonization was the foreign political control of East African territories by European powers.", simpleCheck: "Foreign groups came as traders, missionaries, explorers, settlers and colonial administrators.", categories: [cat("Traders", "people who came to buy and sell goods", ["Arabs", "Portuguese", "Indian traders"]), cat("Missionaries", "religious workers who spread Christianity", ["built schools and hospitals"]), cat("Explorers", "travelers who gathered information about places", ["sources of rivers", "resources"]), cat("Colonialists", "foreign rulers controlling territories", ["British", "Germans"] )], examples: [ex("Positive effect", "Missionaries introduced formal schools and health centres."), ex("Negative effect", "Colonialism led to loss of land and forced labour."), ex("Partition", "European powers divided territories using boundaries." )], facts: ["The Uganda Railway increased British control and transport in East Africa.", "Cash-crop growing expanded under colonial rule.", "African resistance occurred in many places.", "Colonial boundaries sometimes divided communities."], image: { title: "Partition of Africa", imageUrl: "/images/social-studies/partition-of-africa-1884.png", caption: "European partition affected East Africa and the rest of the continent.", labels: ["British", "German", "Belgian", "Portuguese"] }, questions: [short("Define colonization."), short("Name two foreign groups that came to East Africa."), mc("Missionaries mainly spread:", ["Christianity", "volcanoes", "deserts", "latitudes"], "Christianity"), written("Give two negative effects of colonial rule in East Africa.")] })],
  "p6-independence-eac": [lesson({ id: "p6-sst-independence-eac-heavy-v4", term: "Term III", subject: "Social Studies", topicTitle: "Road to Independence and the East African Community", subTopicTitle: "Independence, Nationalism and the East African Community", definition: "Independence is the freedom of a country to govern itself. The East African Community is a regional organisation formed to promote cooperation among member states.", simpleCheck: "Nationalism helped East African countries demand self-rule.", categories: [cat("Nationalism", "love for one's country and desire for self-rule", ["political parties", "trade unions"]), cat("Independence", "self-government", ["Uganda 1962", "Kenya 1963", "Tanzania 1961"]), cat("EAC", "regional organisation for cooperation", ["trade", "movement", "infrastructure", "peace"] )], examples: [ex("Uganda", "Became independent on 9 October 1962."), ex("Kenya", "Jomo Kenyatta was a key nationalist leader."), ex("EAC benefit", "Common markets can increase trade among member states." )], facts: ["Nationalists used parties, petitions, strikes, newspapers and negotiations.", "Independence brought self-rule but also development challenges.", "Regional cooperation can reduce trade barriers.", "EAC organs include the Summit, Council of Ministers, EALA and EAC Court of Justice."], questions: [short("Define independence."), short("When did Uganda become independent?", "9 October 1962."), mc("The EAC mainly promotes:", ["regional cooperation", "slave trade", "desert growth", "isolation"], "regional cooperation"), written("Give three benefits of the East African Community.")] })],
};

export function applyP6MathHeavyV4(topics: Topic[]): Topic[] {
  return applyHeavyV4(topics, P6_MATH_HEAVY_V4);
}

export function applyP6ScienceHeavyV4(topics: Topic[]): Topic[] {
  return applyHeavyV4(topics, P6_SCIENCE_HEAVY_V4);
}

export function applyP6EnglishHeavyV4(topics: Topic[]): Topic[] {
  return applyHeavyV4(topics, P6_ENGLISH_HEAVY_V4);
}

export function applyP6SocialHeavyV4(topics: Topic[]): Topic[] {
  return applyHeavyV4(topics, P6_SOCIAL_HEAVY_V4);
}
